# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://github.com/billsea/specs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'ImplementApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImplementApp
  pod 'TestFramework'

end
